spring:
  application:
    name: shopee-price-history-backend
  profiles:
    active: dev

aws:
  region: ap-southeast-1

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
  sql:
    init:
      platform: postgresql
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/price_history
    driver-class-name: org.postgresql.Driver
    username: app
    password: secret
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true